#!/bin/bash

gcc -std=c11 -o calc calc.c

runtest() {
  output=$(./calc "$1")
  if [ "$output" != "$2" ]; then
    echo "$1 => $2 expected, but got $output"
    exit 1
  fi
  echo "$1 => $output"
}

echo
echo '=== basic ==='
runtest 0 0
runtest 2 2
runtest 20 20
runtest 810 810
runtest 114514 114514
runtest " 3" 3

echo
echo '=== arithmetic ==='
runtest "3+5" 8
runtest "3-5" -2
runtest "3*5" 15
runtest "10/5" 2
runtest "3+4*5*4-10" 73
runtest "P()" 0
runtest "F{1}F()" 1
runtest "F{4*5}F()" 20
runtest "F{4*5}F()*F()" 400
