#!/bin/bash

gcc -std=c11 -g -o calc calc.c

runtest() {
  output=$(./calc "$1")
  if [ "$output" != "$2" ]; then
    echo "$1 => $2 expected, but got $output"
    exit 1
  fi
  echo "$1 => $output"
}

echo
echo '=== basic ==='
runtest 0 0
runtest 2 2
runtest 20 20
runtest 810 810
runtest 114514 114514
runtest " 3" 3

echo
echo '=== arithmetic ==='
runtest "3+5" 8
runtest "3-5" -2
runtest "3*5" 15
runtest "10/5" 2
runtest "3+4*5*4-10" 73

echo
echo '=== functions ==='
runtest "P()" 0
runtest "F{1}F()" 1
runtest "F{4*5}F()" 20
runtest "F{4*5+3}F()*F()" 529

# functions with arguments
runtest "P(1)" 0
runtest "F{a}F(1)" 1
runtest "F{a}F(1+2+3)" 6
runtest "F{a*a}F(2)*F(3)" 36
runtest "F{a*a+a}F(2)" 6
runtest "F{a*a+b}F(3,2)" 11
