#!/bin/zsh

gcc -std=c11 -o calc calc.c

runtest() {
  output=$(./calc "$1")
  if ["$output" != "$2"]; then
    echo "$1: $2 expected, but got $output"
    exit 1
  fi
  echo "$1 => $output"
}

runtest 1 1
